# Form implementation generated from reading ui file '.\add_items.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 498)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 261, 251))
        self.listWidget.setObjectName("listWidget")
        self.item_add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.item_add_button.setGeometry(QtCore.QRect(20, 380, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.item_add_button.setFont(font)
        self.item_add_button.setObjectName("item_add_button")
        self.items_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.items_label.setGeometry(QtCore.QRect(20, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.items_label.setFont(font)
        self.items_label.setObjectName("items_label")
        self.item_textedit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.item_textedit.setGeometry(QtCore.QRect(20, 330, 261, 41))
        self.item_textedit.setObjectName("item_textedit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listWidget, self.item_textedit)
        MainWindow.setTabOrder(self.item_textedit, self.item_add_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.item_add_button.setText(_translate("MainWindow", "Add Item"))
        self.items_label.setText(_translate("MainWindow", "Items List"))
        self.item_textedit.setPlainText(_translate("MainWindow", "Haha"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
