# Form implementation generated from reading ui file '.\connection_wizard.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWizard(object):
    def setupUi(self, ConnectionWizard):
        ConnectionWizard.setObjectName("ConnectionWizard")
        ConnectionWizard.resize(300, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConnectionWizard.sizePolicy().hasHeightForWidth())
        ConnectionWizard.setSizePolicy(sizePolicy)
        ConnectionWizard.setMinimumSize(QtCore.QSize(300, 550))
        ConnectionWizard.setMaximumSize(QtCore.QSize(300, 550))
        ConnectionWizard.setBaseSize(QtCore.QSize(300, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../icons/icon_no_letters.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ConnectionWizard.setWindowIcon(icon)
        self.icon_connection_status = QtWidgets.QLabel(parent=ConnectionWizard)
        self.icon_connection_status.setGeometry(QtCore.QRect(250, 10, 32, 32))
        self.icon_connection_status.setText("")
        self.icon_connection_status.setPixmap(QtGui.QPixmap(".\\../icons/red_led.png"))
        self.icon_connection_status.setScaledContents(True)
        self.icon_connection_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon_connection_status.setObjectName("icon_connection_status")
        self.conn_status_label = QtWidgets.QLabel(parent=ConnectionWizard)
        self.conn_status_label.setGeometry(QtCore.QRect(20, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.conn_status_label.setFont(font)
        self.conn_status_label.setObjectName("conn_status_label")
        self.package_viewer = QtWidgets.QPlainTextEdit(parent=ConnectionWizard)
        self.package_viewer.setGeometry(QtCore.QRect(20, 170, 261, 231))
        self.package_viewer.setPlainText("")
        self.package_viewer.setObjectName("package_viewer")
        self.review_label = QtWidgets.QLabel(parent=ConnectionWizard)
        self.review_label.setGeometry(QtCore.QRect(20, 140, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.review_label.setFont(font)
        self.review_label.setObjectName("review_label")
        self.send_packages_button = QtWidgets.QPushButton(parent=ConnectionWizard)
        self.send_packages_button.setGeometry(QtCore.QRect(20, 420, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.send_packages_button.setFont(font)
        self.send_packages_button.setObjectName("send_packages_button")
        self.connect_button = QtWidgets.QPushButton(parent=ConnectionWizard)
        self.connect_button.setGeometry(QtCore.QRect(20, 50, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.disconnect_button = QtWidgets.QPushButton(parent=ConnectionWizard)
        self.disconnect_button.setGeometry(QtCore.QRect(20, 90, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.disconnect_button.setFont(font)
        self.disconnect_button.setObjectName("disconnect_button")

        self.retranslateUi(ConnectionWizard)
        QtCore.QMetaObject.connectSlotsByName(ConnectionWizard)
        ConnectionWizard.setTabOrder(self.connect_button, self.package_viewer)
        ConnectionWizard.setTabOrder(self.package_viewer, self.send_packages_button)

    def retranslateUi(self, ConnectionWizard):
        _translate = QtCore.QCoreApplication.translate
        ConnectionWizard.setWindowTitle(_translate("ConnectionWizard", "Communication Wizard"))
        self.conn_status_label.setText(_translate("ConnectionWizard", "Connection Status:"))
        self.review_label.setText(_translate("ConnectionWizard", "Review Package"))
        self.send_packages_button.setText(_translate("ConnectionWizard", "Send Packages"))
        self.connect_button.setToolTip(_translate("ConnectionWizard", "<html><head/><body><p>Attempt to connect (or reconnect)</p></body></html>"))
        self.connect_button.setText(_translate("ConnectionWizard", "Connect"))
        self.disconnect_button.setToolTip(_translate("ConnectionWizard", "<html><head/><body><p>Attempt to connect (or reconnect)</p></body></html>"))
        self.disconnect_button.setText(_translate("ConnectionWizard", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConnectionWizard = QtWidgets.QWidget()
    ui = Ui_ConnectionWizard()
    ui.setupUi(ConnectionWizard)
    ConnectionWizard.show()
    sys.exit(app.exec())
